### ISSUE TITLE
chaosazure machine probes - TypeError

### ISSUE THREAD

**Issue by SRAM85** [chaostoolkit/chaostoolkit-lib#121]
i am trying the azure module probe to get the count of machines. i am setting up the tolerance as int as that is the return type from the function but i end up with an error 

"steady-state-hypothesis": {
    "title": "Count of VMS should always be 5 which is desired state",
    "probes": [
      {
       "provider": {
         "func": "count_machines",
          "module": "chaosazure.machine.probes",
          "type": "python"
          },
       "name": "count-machines",
       "tolerance": 5,
       "type": "probe"
      }
    ]
  }

[2019-05-19 13:39:25 INFO] Validating the experiment's syntax
[2019-05-19 13:39:25 INFO] Experiment looks valid
[2019-05-19 13:39:25 INFO] Running experiment: How does my platform behave when underlying vms are unhealthy and restarts multiple ti
mes
[2019-05-19 13:39:25 INFO] Steady state hypothesis: Count of VMS should always be 5 which is desired state
[2019-05-19 13:39:25 INFO] Probe: count-machines
[2019-05-19 13:39:25 ERROR]   => failed: TypeError: can only concatenate str (not "NoneType") to str
[2019-05-19 13:39:25 WARNING] Probe terminated unexpectedly, so its tolerance could not be validated
[2019-05-19 13:39:25 CRITICAL] Steady state probe 'count-machines' is not in the given tolerance so failing this experiment

[2019-05-19 13:39:25 INFO] Let's rollback...
[2019-05-19 13:39:25 INFO] No declared rollbacks, let's move on.
[2019-05-19 13:39:25 INFO] Experiment ended with status: failed

**Comment by buderre** [comment]
@SRAM85 : Thank your for the report. Can you take a look at the *.log file for any interesting details? Indeed it may be related to the Azure extension.

**Comment by SRAM85** [comment]
@buderre , sure below is what i see in the logs.

[36m[2019-05-19 13:39:25 DEBUG][39m Activity failed
    Traceback (most recent call last):
      File "/Users/skramal/anaconda3/lib/python3.7/site-packages/chaoslib/provider/python.py", line 55, in run_python_activity
        return func(**arguments)
      File "/Users/skramal/anaconda3/lib/python3.7/site-packages/chaosazure/machine/probes.py", line 51, in count_machines
        machines = fetch_resources(filter, RES_TYPE_VM, secrets, configuration)
      File "/Users/skramal/anaconda3/lib/python3.7/site-packages/chaosazure/rgraph/resource_graph.py", line 8, in fetch_resources
        with auth(secrets) as cred:
      File "/Users/skramal/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "/Users/skramal/anaconda3/lib/python3.7/site-packages/chaosazure/__init__.py", line 60, in auth
        credentials = __get_credentials(creds)
      File "/Users/skramal/anaconda3/lib/python3.7/site-packages/chaosazure/__init__.py", line 84, in __get_credentials
        tenant=creds['azure_tenant_id']
      File "/Users/skramal/anaconda3/lib/python3.7/site-packages/msrestazure/azure_active_directory.py", line 354, in __init__
        self.set_token()
      File "/Users/skramal/anaconda3/lib/python3.7/site-packages/msrestazure/azure_active_directory.py", line 361, in set_token
        super(ServicePrincipalCredentials, self).set_token()
      File "/Users/skramal/anaconda3/lib/python3.7/site-packages/msrestazure/azure_active_directory.py", line 187, in set_token
        self._create_adal_context()
      File "/Users/skramal/anaconda3/lib/python3.7/site-packages/msrestazure/azure_active_directory.py", line 108, in _create_adal_context
        authority_url = authority_url + '/' + self._tenant
    TypeError: can only concatenate str (not "NoneType") to str
    
    During handling of the above exception, another exception occurred:

**Comment by SRAM85** [comment]
@buderre , Looks like this exception is from the function _create_adal_context in the module azure_active_directory.py  . i rechecked the  ServicePrincipalCredentials and it works fine when using triggering the actions like start_machines or restart_machines.

**Comment by buderre** [comment]
@SRAM85 : Can you also give me an excerpt of your experiment file? Please remove the credentials :)
And also which version of the azure-extension you are using together with the version of the chaostoolkit that you use.

I could try it then with the same configuration. Thank you in advance

**Comment by SRAM85** [comment]
@buderre : chaostoolkit-azure Version: 0.4.0

**Comment by SRAM85** [comment]
@buderre , were you able try this setup ? would be interested to know if i am missing something in my execution.

**Comment by buderre** [comment]
@SRAM85 : I am sorry. I wasn't even at the desk the last four days. I just started this week to work again :). I will investigate asap - I did not forget this issue ;)

I'll keep you up to date

**Comment by buderre** [comment]
@SRAM85 : Could you please provide the secrets and configuration for the count_machines function too and try it again?

**Comment by SRAM85** [comment]
@buderre , i figured out what was going on . The  probe requires secrets and config to be passed and i tried passing them just like action method. 

"steady-state-hypothesis": {
      "title": "Count of VMS should always be 20 which is desired state",
      "probes": [
        {
         "provider": {
           "func": "count_machines",
           "arguments": {
                    "filter": "where resourceGroup=='gieo-sre' and tags.project_name=~'Azure-Chaos-Monkey'"
                  },
            "module": "chaosazure.machine.probes",
            "type": "python",
            "secrets": ["azure"],
            "config": ["azure"]
            },
         "name": "count-machines",
         "type": "probe",
         "tolerance":10
        }
      ]
    }

Am not sure if this can be optional or not. If this is mandatory then we should be adding this to the documentation.

**Comment by SRAM85** [comment]
This is good stuff, we are looking at writing functions for other resources in the future and contribute.

**Comment by buderre** [comment]
@SRAM85 Thank you for the feedback. We are always looking forward for more features and abilities and a nice audience :)

I created an [issue](https://github.com/chaostoolkit-incubator/chaostoolkit-azure/issues/57) for it and will suggest to close this issue.

**Comment by Lawouach** [comment]
Thanks @buderre for leading this! Much appreciated.

Thanks @SRAM85 for sticking with the toolkit! :)
