### ISSUE TITLE
chao run is failing to run "got an unexpected keyword argument 'continous_hypothesis_frequency'"

### ISSUE THREAD

**Issue by nitinkansal1984** [chaostoolkit/chaostoolkit-lib#228]
**Describe the bug**

[2021-08-24 06:40:58 INFO] Validating the experiment's syntax
[2021-08-24 06:40:58 INFO] Experiment looks valid
Traceback (most recent call last):
  File "/root/.venvs/chaostk/bin/chaos", line 11, in <module>
    sys.exit(cli())
  File "/root/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/root/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/root/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.venvs/chaostk/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/root/.venvs/chaostk/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/.venvs/chaostk/lib/python3.6/site-packages/chaostoolkit/cli.py", line 185, in run
    fail_fast=fail_fast)
TypeError: __init__() got an unexpected keyword argument 'continous_hypothesis_frequency'

**Runtime versions**
Please run:
chaos, version 1.9.2

```
$ python --version
Python 3.6.9
$ chaos info core
NAME                VERSION
CLI                 1.9.2
Core library        1.21.0
$ chaos info extensions
```

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Additional context**

@CharlieMoon37

**Comment by ciaranevans** [comment]
Hey @nitinkansal1984, apologies for putting you in this situation!

We released a new version of `chaostoolkit-lib` but didn't quite get around to releasing its counterpart `chaostoolkit` release.

I've just done that now, could you try re-installing `chaostoolkit`?

```
pip install -U chaostoolkit
```

You should then get `chaostoolkit==1.9.3` 🚀

**Comment by nitinkansal1984** [comment]
its working now ! Thanks for the fix !

**Comment by ciaranevans** [comment]
@nitinkansal1984 awesome, glad to hear, i'll close this now

Again, sorry we caught you out!
