### ISSUE TITLE
Error in python 3.11

### ISSUE THREAD

**Issue by wride95** [chaostoolkit/chaostoolkit-lib#268]
(chaostk-env) C:\Users\Administrator\Desktop\chaostoolkit-aws>pip install chaoslib
Collecting chaoslib
Using cached chaoslib-0.0.1-Alpha.tar.gz (2.1 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing metadata (pyproject.toml) ... done
Collecting randomdotorg (from chaoslib)
Using cached randomdotorg-0.1.3a3.tar.gz (4.0 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [23 lines of output]
Traceback (most recent call last):
File "C:\Users\Administrator\chaostk-env\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 353, in
main()
File "C:\Users\Administrator\chaostk-env\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Administrator\chaostk-env\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 118, in get_requires_for_build_wheel
return hook(config_settings)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-1u1de5f0\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
return self._get_build_requires(config_settings, requirements=['wheel'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-1u1de5f0\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
self.run_setup()
File "C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-1u1de5f0\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
File "C:\Users\Administrator\AppData\Local\Temp\2\pip-build-env-1u1de5f0\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
exec(code, locals())
File "", line 22, in
File "C:\Users\Administrator\AppData\Local\Temp\2\pip-install-ku68zsv5\randomdotorg_bcb281763b1047a698e8cdf34ab27ef3\randomdotorg.py", line 187
raise ValueError, "sample larger than population"
^
SyntaxError: invalid syntax
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Getting the above error for Python 3.11.4

**Comment by Lawouach** [comment]
Hello @wride95 

`chaoslib` is not a Chaos Toolkit project. This should be `pip install chaostoolkit-lib`
